services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=filemanager
      - DB_USERNAME=filemanager
      - DB_PASSWORD=filemanager
    volumes:
      - ./:/var/www/html:cached
      - exclude-storage-link:/var/www/html/public/storage
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: filemanager
      MYSQL_USER: filemanager
      MYSQL_PASSWORD: filemanager
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  exclude-storage-link: